### ISSUE TITLE
dndDragover class is not removed every times the pointer left the drag aera.

### ISSUE THREAD

**Issue by Lospepes** [misha130/ngx-drag-and-drop-lists#14]
Hello,

First of all, thank you for your work.

I don't understand why the dndDragOver class doesn't remove itself sometimes when the pointer leaves the bottom of the drag area or leaves the right of the drag area.

So the dndPlaceHolder does not delete itself and no event is triggered. I think the problem comes from a mistake from me because it works perfectly on your demo. 

Do you have an idea to solve this problem please?

Thanks in advance

**Comment by Dioude** [comment]
Hello, 
I've noticed the same issue because i'm using horizontal list (photo grid).
When moving from left to right the class trigger when i'm on the bottom half of the hovered div, and when moving from right to left it triggers when i'm hovering the top half. 
You can also see this on the demo with vertical lists but it's a bit less obvious.

No solutions so far, is it possible to have a parameter to use horizontal or vertical detection ?
